
package uasInv;

import dbconnect.connect;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author farid.arrido
 */
public class mstBarang extends javax.swing.JFrame {
    private void update_tabel(){
        
        
        try {
           
            java.sql.Connection conn=dbconnect.connect.connectDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet sql=stm.executeQuery("select * from mst_barang");
            
            tbl_mstBarang.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e) {
        }
    }
    /**
     * Creates new form mstBarang
     */
    public mstBarang() {
        initComponents();
        update_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txt_kdBarang = new javax.swing.JTextField();
        lbl_kdBarang = new javax.swing.JLabel();
        lbl_nmBarang = new javax.swing.JLabel();
        lbl_satuan = new javax.swing.JLabel();
        txt_nmBarang = new javax.swing.JTextField();
        txt_satuan = new javax.swing.JTextField();
        b_Simpan = new javax.swing.JButton();
        b_Edit = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mstBarang = new javax.swing.JTable();
        b_Batal = new javax.swing.JButton();
        b_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MASTER BARANG");
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(750, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_kdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 139, -1));

        lbl_kdBarang.setText("Kode barang");
        getContentPane().add(lbl_kdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lbl_nmBarang.setText("Nama barang");
        getContentPane().add(lbl_nmBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lbl_satuan.setText("Satuan");
        getContentPane().add(lbl_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(txt_nmBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 139, -1));
        getContentPane().add(txt_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 139, -1));

        b_Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input.png"))); // NOI18N
        b_Simpan.setText("Simpan");
        b_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(b_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        b_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        b_Edit.setText("Edit");
        b_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EditActionPerformed(evt);
            }
        });
        getContentPane().add(b_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 40));

        b_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(b_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 40));

        tbl_mstBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mstBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mstBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mstBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 220));

        b_Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset1.png"))); // NOI18N
        b_Batal.setText("Batal");
        b_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_BatalActionPerformed(evt);
            }
        });
        getContentPane().add(b_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 90, 40));

        b_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back_2.png"))); // NOI18N
        b_kembali.setText("Kembali");
        b_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(b_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, 30));

        pack();
    }// </editor-fold>                        

    private void tbl_mstBarangMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        try {
                int row=tbl_mstBarang.rowAtPoint(evt.getPoint());
                String kd_barang=tbl_mstBarang.getValueAt(row,0).toString();
                txt_kdBarang.setText(String.valueOf(kd_barang));
                String nama_barang=tbl_mstBarang.getValueAt(row,1).toString();
                txt_nmBarang.setText(String.valueOf(nama_barang));
                String satuan=tbl_mstBarang.getValueAt(row,2).toString();
                txt_satuan.setText(String.valueOf(satuan));
                       
        } catch (Exception e) {
        }
    }                                          

    private void b_SimpanActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {
        String sql = "insert into mst_barang values('"+txt_kdBarang.getText()+"','"+txt_nmBarang.getText()+"','"+txt_satuan.getText()+"')";
        java.sql.Connection conn = dbconnect.connect.connectDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "berhasil disimpan");
        
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txt_kdBarang.setText("");
        txt_nmBarang.setText("");
        txt_satuan.setText("");
        
        update_tabel();
    
    }                                        

    private void b_EditActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        try {
            String quary="update mst_barang set kd_barang='"+txt_kdBarang.getText()+"',nama_barang='"+txt_nmBarang.getText()+"',satuan='"+txt_satuan.getText()+"' where kd_barang='"+txt_kdBarang.getText()+"'";
            java.sql.Connection conn=dbconnect.connect.connectDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(quary);
            pst.executeUpdate(quary);
            JOptionPane.showMessageDialog(null,"data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"gagal edit " +e.getMessage());
        }
     
        txt_kdBarang.setText("");
        txt_nmBarang.setText("");
        txt_satuan.setText("");
        
        update_tabel();
            
    
    }                                      

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        try {
            String sql ="delete from mst_barang where kd_barang=? ";
            java.sql.Connection conn = dbconnect.connect.connectDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txt_kdBarang.getText());
            pst.execute();
            
            
            JOptionPane.showMessageDialog(null, "hapus");
            txt_kdBarang.setText("");
            txt_nmBarang.setText("");
            txt_satuan.setText("");
            
            
        } catch (Exception e) {
        }
        update_tabel();
    }                                       

    private void b_BatalActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txt_kdBarang.setText("");
        txt_nmBarang.setText("");
        txt_satuan.setText("");
        
    }                                       

    private void b_kembaliActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        new uasInv.mainApp().setVisible(true); 
        this.dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mstBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mstBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mstBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mstBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mstBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b_Batal;
    private javax.swing.JButton b_Edit;
    private javax.swing.JButton b_Simpan;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_kembali;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_kdBarang;
    private javax.swing.JLabel lbl_nmBarang;
    private javax.swing.JLabel lbl_satuan;
    private javax.swing.JTable tbl_mstBarang;
    private javax.swing.JTextField txt_kdBarang;
    private javax.swing.JTextField txt_nmBarang;
    private javax.swing.JTextField txt_satuan;
    // End of variables declaration                   
}
